<a href="https://colab.research.google.com/github/Hrishabh96/ArtificalNeuralNetwork/blob/main/ArtificalNeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Artifical Neural Network

Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

#Part 1 - Data Preprocessing

Importing the DataSet

In [3]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

#Part 2 - Building the ANN

Initializing the ANN

In [6]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer 

In [7]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Adding the second hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Adding the output layer

In [9]:
ann.add(tf.keras.layers.Dense(units = 1))

#Part 3 - Training the ANN

Compiling the ANN

In [10]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

Training the ANN model on the Training set

In [11]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 849us/step - loss: 9237.2617
Epoch 2/100
240/240 [==============================] - 0s 848us/step - loss: 70.3365
Epoch 3/100
240/240 [==============================] - 0s 812us/step - loss: 68.3341
Epoch 4/100
240/240 [==============================] - 0s 829us/step - loss: 66.0929
Epoch 5/100
240/240 [==============================] - 0s 817us/step - loss: 63.7087
Epoch 6/100
240/240 [==============================] - 0s 865us/step - loss: 60.9199
Epoch 7/100
240/240 [==============================] - 0s 919us/step - loss: 58.5514
Epoch 8/100
240/240 [==============================] - 0s 798us/step - loss: 55.8093
Epoch 9/100
240/240 [==============================] - 0s 811us/step - loss: 53.3910
Epoch 10/100
240/240 [==============================] - 0s 837us/step - loss: 50.9880
Epoch 11/100
240/240 [==============================] - 0s 814us/step - loss: 49.2394
Epoch 12/100
240/240 [==============================] - 0s 83

Predicting the results of the Test set

In [12]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision = 2)
np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)

array([[432.77, 431.23],
       [463.82, 460.01],
       [467.32, 461.14],
       ...,
       [474.53, 473.26],
       [441.37, 438.  ],
       [460.54, 463.28]])